# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vis.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 631)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 5)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(300, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color:rgb(235, 235, 235)\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_video = QtWidgets.QLabel(self.frame)
        self.label_video.setMinimumSize(QtCore.QSize(0, 250))
        self.label_video.setStyleSheet("QLabel{\n"
"    background-color:rgb(255, 255, 255)\n"
"}")
        self.label_video.setText("")
        self.label_video.setObjectName("label_video")
        self.verticalLayout.addWidget(self.label_video)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.frame_4)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color:rgb(199, 199, 199);\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"    height: 25px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color:rgb(157, 157, 157);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 1, 2, 1)
        self.select_MsaModels = QtWidgets.QComboBox(self.frame_4)
        self.select_MsaModels.setObjectName("select_MsaModels")
        self.select_MsaModels.addItem("")
        self.select_MsaModels.addItem("")
        self.select_MsaModels.addItem("")
        self.gridLayout_2.addWidget(self.select_MsaModels, 2, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textBrowser_res = QtWidgets.QTextBrowser(self.frame_5)
        self.textBrowser_res.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowser_res.setStyleSheet("QTextBrowser{\n"
"    text-align: right\n"
"}")
        self.textBrowser_res.setObjectName("textBrowser_res")
        self.verticalLayout_3.addWidget(self.textBrowser_res)
        self.show_feature = QtWidgets.QLabel(self.frame_5)
        self.show_feature.setMinimumSize(QtCore.QSize(20, 175))
        self.show_feature.setMaximumSize(QtCore.QSize(300, 200))
        self.show_feature.setStyleSheet("QLabel{\n"
"    background-color:rgb(255, 255, 255)\n"
"}")
        self.show_feature.setText("")
        self.show_feature.setObjectName("show_feature")
        self.verticalLayout_3.addWidget(self.show_feature)
        self.gridLayout_2.addWidget(self.frame_5, 0, 0, 1, 2)
        self.verticalLayout.addWidget(self.frame_4)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton_start = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_start.setGeometry(QtCore.QRect(30, 6, 75, 23))
        self.pushButton_start.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_start.setStyleSheet("QPushButton{\n"
"    background-color:rgb(199, 199, 199);\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"    height: 25px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color:rgb(157, 157, 157);\n"
"}")
        self.pushButton_start.setObjectName("pushButton_start")
        self.gridLayout.addWidget(self.frame_3, 1, 0, 1, 2)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setStyleSheet("QFrame{\n"
"    background-color:rgb(235, 235, 235);\n"
"    border-left: 0.5px dashed\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame_2)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(420, 40))
        self.plainTextEdit.setStyleSheet("QPlainTextEdit{\n"
"background-color:rgb(255, 255, 255)\n"
"}")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_3.addWidget(self.plainTextEdit, 1, 0, 1, 1)
        self.Button_emit = QtWidgets.QPushButton(self.frame_2)
        self.Button_emit.setMinimumSize(QtCore.QSize(20, 0))
        self.Button_emit.setStyleSheet("QPushButton{\n"
"    background-color:rgb(199, 199, 199);\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"    height: 25px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color:rgb(157, 157, 157);\n"
"}")
        self.Button_emit.setObjectName("Button_emit")
        self.gridLayout_3.addWidget(self.Button_emit, 1, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.frame_2)
        self.scrollArea.setStyleSheet("border:initial;\n"
"border: 0px solid;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 464, 530))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.frame_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "大语言模型"))
        self.pushButton.setText(_translate("MainWindow", "确认"))
        self.select_MsaModels.setItemText(0, _translate("MainWindow", "情感分析模型"))
        self.select_MsaModels.setItemText(1, _translate("MainWindow", "lf_dnn"))
        self.select_MsaModels.setItemText(2, _translate("MainWindow", "tgmn"))
        self.pushButton_start.setText(_translate("MainWindow", "start"))
        self.Button_emit.setText(_translate("MainWindow", "发送"))
